((problem SPS)
  (:domain SPS)
  (:objects
    human1 robot1 cart - agent
    location0a location1a location2a location3a location0b location1b location2b location3b location0c location1c location2c location3c - location
    part1a part1b part1c part1d part1ab part1abc part1abcd part2 part3 part4 - part
    rhand1 lhand1 robothand1 part1abcd_holder part2_holder part3_holder part4_holder - holder
  )
  (:init
    (neighbor location0b location1b) (neighbor location1b location2b) (neighbor location2b location3b)
    (neighbor location1b location0b) (neighbor location2b location1b) (neighbor location3b location2b)
    (neighbor location0a location0b) (neighbor location1a location1b) (neighbor location2a location2b) (neighbor location3a location3b)
    (neighbor location0b location0a) (neighbor location1b location1a) (neighbor location2b location2a) (neighbor location3b location3a)
    (neighbor location0c location1c) (neighbor location1c location2c) (neighbor location2c location3c)
    (neighbor location1c location0c) (neighbor location2c location1c) (neighbor location3c location2c)
    (neighbor location0b location0c) (neighbor location1b location1c) (neighbor location2b location2c) (neighbor location3b location3c)
    (neighbor location0c location0b) (neighbor location1c location1b) (neighbor location2c location2b) (neighbor location3c location3b)
    (getnew part1a part1b part1ab)
    (getnew part1ab part1c part1abc)
    (getnew part1abc part1d part1abcd)
    (locate part1a location0a)
    (locate part1b location1a)
    (locate part1c location1a)
    (locate part1d location1a)
    (locate part2 location1a)
    (locate part3 location2a)
    (locate part4 location3a)
    (at human1 location0b)
    (at robot1 location1b)
    (at cart location0c)
    (free rhand1)
    (free lhand1)
    (free robothand1)
    (free part1abcd_holder)
    (free part2_holder)
    (free part3_holder)
    (free part4_holder)
    (occupied location0b)
    (occupied location1b)
    (occupied location0a)
    (occupied location1a)
    (occupied location2a)
    (occupied location3a)
    (belong human1 lhand1)
    (belong human1 rhand1)
    (belong robot1 robothand1)
    (belong cart part1abcd_holder)
    (belong cart part2_holder)
    (belong cart part3_holder)
    (belong cart part4_holder)
  )

  (:goal
    (and
    (on part1abcd part1abcd_holder) (on part2 part2_holder) (on part3 part3_holder) (on part4 part4_holder)
    )
  )
)