((problem SPS)
  (:domain SPS)
  (:objects
    human1 cart - agent
    location0a location1a location2a location3a location4a location0b location1b location2b location3b  location4b location0c location1c location2c location3c location4c - location
    part1 part2a part2b part2c part2d part2ab part2abc part2abcd part2 part3 part4 - part
    rhand1 lhand1 part1_holder part2abcd_holder part3_holder part4_holder - holder
  )
  (:init
    (neighbor location0b location1b) (neighbor location1b location2b) (neighbor location2b location3b) (neighbor location3b location4b)
    (neighbor location1b location0b) (neighbor location2b location1b) (neighbor location3b location2b) (neighbor location4b location3b)
    (neighbor location0a location0b) (neighbor location1a location1b) (neighbor location2a location2b) (neighbor location3a location3b) (neighbor location4a location4b)
    (neighbor location0b location0a) (neighbor location1b location1a) (neighbor location2b location2a) (neighbor location3b location3a) (neighbor location4b location4a)
    (neighbor location0c location1c) (neighbor location1c location2c) (neighbor location2c location3c) (neighbor location3c location4c)
    (neighbor location1c location0c) (neighbor location2c location1c) (neighbor location3c location2c) (neighbor location4c location3c)
    (neighbor location0b location0c) (neighbor location1b location1c) (neighbor location2b location2c) (neighbor location3b location3c) (neighbor location4b location4c)
    (neighbor location0c location0b) (neighbor location1c location1b) (neighbor location2c location2b) (neighbor location3c location3b) (neighbor location4c location4b)
    (getnew part2a part2b part2ab)
    (getnew part2ab part2c part2abc)
    (getnew part2abc part2d part2abcd)
    (locate part1 location1a)
    (locate part2a location2a)
    (locate part2b location2a)
    (locate part2c location2a)
    (locate part2d location2a)
    (locate part3 location3a)
    (locate part4 location3a)
    (at human1 location0b)
    (at cart location0c)
    (free rhand1)
    (free lhand1)
    (free part1_holder)
    (free part2abcd_holder)
    (free part3_holder)
    (free part4_holder)
    (occupied location0a)
    (occupied location1a)
    (occupied location2a)
    (occupied location3a)
    (occupied location4a)
    (occupied location0b)
    (occupied location0c)
    (belong human1 lhand1)
    (belong human1 rhand1)
    (belong cart part1_holder)
    (belong cart part2abcd_holder)
    (belong cart part3_holder)
    (belong cart part4_holder)
  )

  (:goal
    (and
    (on part1 part1_holder) (on part2abcd part2abcd_holder) (on part3 part3_holder) (on part4 part4_holder)
    )
  )
)